org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# minecraft + forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# dependencies
appleskin_file_id=4770828

# mod
mod_id=hungeroverhauled
mod_name=Hunger Overhauled
mod_license=MIT
mod_version=2.2
mod_group_id=io.github.smokahs.hungeroverhauled
mod_authors=iguanaman, progwml6, Parker8283, squeek502, smokahs
mod_description=Makes food and farming matter again. A 1.20.1 port of the classic Hunger Overhaul.
